### Install dependencies

In [1]:
import requests
import os 
from dotenv import load_dotenv
import time
import pandas as pd
from sqlalchemy import create_engine, text
from sklearn.preprocessing import MinMaxScaler

KeyboardInterrupt:

In [ ]:
load_dotenv()

# API key for TMDB API
API_KEY = os.getenv("TMDB_API_KEY")


# Function to get popular movies information
def get_movies_information(oage):

    # Endpoint for popular movies
    url = "https://api.themoviedb.org/3/movie/popular"

    params = {
        "api_key": API_KEY,
        "language": "en-US",
        "page": page
    }

    response = requests.get(url, params=params)

    if response.status_code != 200:
        print(f"Error: {response.status_code}")
        return []

    return response.json()["results"]

all_movies = []

# We will fetch the first 100 pages of popular movies.
for page in range(1, 101):
    print(f"Dowloading page {page}...")
    movies = get_movies_information(page)
    all_movies.extend(movies)

    time.sleep(0.25) # Sleep for 250ms to avoid hitting the rate limit
          
print("Films information: ", len(all_movies))

Dowloading page 1...
Dowloading page 2...
Dowloading page 3...
Dowloading page 4...
Dowloading page 5...
Dowloading page 6...
Dowloading page 7...
Dowloading page 8...
Dowloading page 9...
Dowloading page 10...
Dowloading page 11...
Dowloading page 12...
Dowloading page 13...
Dowloading page 14...
Dowloading page 15...
Dowloading page 16...
Dowloading page 17...
Dowloading page 18...
Dowloading page 19...
Dowloading page 20...
Dowloading page 21...
Dowloading page 22...
Dowloading page 23...
Dowloading page 24...
Dowloading page 25...
Dowloading page 26...
Dowloading page 27...
Dowloading page 28...
Dowloading page 29...
Dowloading page 30...
Dowloading page 31...
Dowloading page 32...
Dowloading page 33...
Dowloading page 34...
Dowloading page 35...
Dowloading page 36...
Dowloading page 37...
Dowloading page 38...
Dowloading page 39...
Dowloading page 40...
Dowloading page 41...
Dowloading page 42...
Dowloading page 43...
Dowloading page 44...
Dowloading page 45...
Dowloading page 46...
Dowloading page 47...
Dowloading page 48...
Dowloading page 49...
Dowloading page 50...
Dowloading page 51...
Dowloading page 52...
Dowloading page 53...
Dowloading page 54...
Dowloading page 55...
Dowloading page 56...
Dowloading page 57...
Dowloading page 58...
Dowloading page 59...
Dowloading page 60...
Dowloading page 61...
Dowloading page 62...
Dowloading page 63...
Dowloading page 64...
Dowloading page 65...
Dowloading page 66...
Dowloading page 67...
Dowloading page 68...
Dowloading page 69...
Dowloading page 70...
Dowloading page 71...
Dowloading page 72...
Dowloading page 73...
Dowloading page 74...
Dowloading page 75...
Dowloading page 76...
Dowloading page 77...
Dowloading page 78...
Dowloading page 79...
Dowloading page 80...
Dowloading page 81...
Dowloading page 82...
Dowloading page 83...
Dowloading page 84...
Dowloading page 85...
Dowloading page 86...
Dowloading page 87...
Dowloading page 88...
Dowloading page 89...
Dowloading page 90...
Dowloading page 91...
Dowloading page 92...
Dowloading page 93...
Dowloading page 94...
Dowloading page 95...
Dowloading page 96...
Dowloading page 97...
Dowloading page 98...
Dowloading page 99...
Dowloading page 100...
Films information:  2000

In [24]:
all_movies

[{'adult': False,
  'backdrop_path': '/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg',
  'genre_ids': [10751, 35, 12, 14, 16],
  'id': 1226863,
  'original_language': 'en',
  'original_title': 'The Super Mario Galaxy Movie',
  'overview': "Having thwarted Bowser's previous plot to marry Princess Peach, Mario and Luigi now face a fresh threat in Bowser Jr., who is determined to liberate his father from captivity and restore the family legacy. Alongside companions new and old, the brothers travel across the stars to stop the young heir's crusade.",
  'popularity': 828.4621,
  'poster_path': '/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg',
  'release_date': '2026-04-01',
  'title': 'The Super Mario Galaxy Movie',
  'video': False,
  'vote_average': 6.8,
  'vote_count': 529},
 {'adult': False,
  'backdrop_path': '/1x9e0qWonw634NhIsRdvnneeqvN.jpg',
  'genre_ids': [10749, 18],
  'id': 1523145,
  'original_language': 'ru',
  'original_title': 'Твоё сердце будет разбито',
  'overview': 'High school student Polina is saved from bullying at her new school and makes a deal with the main bully Bars: he must pretend to be her boyfriend and protect her, and she must do everything he says. During this game, the couple develops real feelings, but her family and classmates have reasons to separate the lovers.',
  'popularity': 434.1481,
  'poster_path': '/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg',
  'release_date': '2026-03-26',
  'title': 'Your Heart Will Be Broken',
  'video': False,
  'vote_average': 6.985,
  'vote_count': 66},
 {'adult': False,
  'backdrop_path': '/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg',
  'genre_ids': [878, 12, 14],
  'id': 83533,
  'original_language': 'en',
  'original_title': 'Avatar: Fire and Ash',
  'overview': "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
  'popularity': 329.658,
  'poster_path': '/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg',
  'release_date': '2025-12-17',
  'title': 'Avatar: Fire and Ash',
  'video': False,
  'vote_average': 7.4,
  'vote_count': 2650},
 {'adult': False,
  'backdrop_path': '/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg',
  'genre_ids': [16, 28, 12, 14],
  'id': 980431,
  'original_language': 'en',
  'original_title': 'Avatar: Aang, The Last Airbender',
  'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
  'popularity': 316.0527,
  'poster_path': '/gPiyTLo5GGwtJl0L8TlaJF9r0KE.jpg',
  'release_date': '2026-10-09',
  'title': 'Avatar: Aang, The Last Airbender',
  'video': False,
  'vote_average': 0.0,
  'vote_count': 0},
 {'adult': False,
  'backdrop_path': '/gM1kQRPwOVW1Eos5tVWqcYmHR5S.jpg',
  'genre_ids': [27, 9648],
  'id': 1470130,
  'original_language': 'en',
  'original_title': 'The Mortuary Assistant',
  'overview': 'Rebecca Owens, a recent mortuary science graduate takes a night shift job at River Fields Mortuary. Initially, the job seems straightforward — embalming bodies, completing paperwork, and keeping things tidy. But once Rebecca starts working the night shift, things take a dark turn.',
  'popularity': 263.8668,
  'poster_path': '/72AoFPC5TY4DfJwXXS9rPwPeReD.jpg',
  'release_date': '2026-02-13',
  'title': 'The Mortuary Assistant',
  'video': False,
  'vote_average': 5.4,
  'vote_count': 76},
 {'adult': False,
  'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction… but an unexpected friendship means he may not have to do it alone.',
  'popularity': 262.4292,
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'release_date': '2026-03-15',
  'title': 'Project Hail Mary',
  'video': False,
  'vote_average': 8.215,
  'vote_count': 1571},
 {'adult': False,
  'backdrop_path': '/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg',
  'genre_ids': [16, 10751, 878, 35, 12],
  'id': 1327819,
  'original_language': 'en',
  'original_title': 'Hoppers',
  'overview': "Scientists have discovered how to 'hop' human consciousness into lifelike robotic animals, allowing people to communicate with animals as animals. Animal lover Mabel seizes an opportunity to use the technology, uncovering mysteries within the animal world beyond anything she could have imagined.",
  'popularity': 226.1527,
  'poster_path': '/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg',
  'release_date': '2026-03-04',
  'title': 'Hoppers',
  'video': False,
  'vote_average': 7.587,
  'vote_count': 485},
 {'adult': False,
  'backdrop_path': '/3ooXDVaz4xHKtwe4lkmF1gNopOC.jpg',
  'genre_ids': [27, 53],
  'id': 1290417,
  'original_language': 'en',
  'original_title': 'Thrash',
  'overview': 'When a Category 5 hurricane decimates a coastal town, the storm surge brings devastation, chaos, and something far more frightening onto shore: hungry sharks.',
  'popularity': 206.5751,
  'poster_path': '/adk8weka3O5648g3de4z3y4aE7G.jpg',
  'release_date': '2026-04-10',
  'title': 'Thrash',
  'video': False,
  'vote_average': 6.017,
  'vote_count': 347},
 {'adult': False,
  'backdrop_path': '/bYkgJUGlkDrKzCrN6Jrd1qVx9aB.jpg',
  'genre_ids': [35, 10749],
  'id': 20222,
  'original_language': 'es',
  'original_title': 'Sexo con amor',
  'overview': 'In Santiago, Chile, the schoolteacher Luisa proposes a debate about sex with the parents of her students with the intention of giving classes about sex education to the youngsters.',
  'popularity': 286.2109,
  'poster_path': '/9Unz4SnlkXg0OAxgiLKZAfu096c.jpg',
  'release_date': '2003-03-27',
  'title': 'Sex with Love',
  'video': False,
  'vote_average': 6.519,
  'vote_count': 241},
 {'adult': False,
  'backdrop_path': '/jRsjWwZzI39bTm44FNhRtiICd9k.jpg',
  'genre_ids': [35, 28, 12],
  'id': 1084577,
  'original_language': 'en',
  'original_title': 'Balls Up',
  'overview': 'Two marketing executives go "balls out" and pitch a bold full‑coverage condom sponsorship with the World Cup. After their drunken celebration in Brazil sparks a global scandal, they must outrun furious fans, criminals, and power-hungry officials to salvage their careers and make it home alive.',
  'popularity': 214.69,
  'poster_path': '/xwvJ3WzdJ1OCuDoY8LAxBUlQyig.jpg',
  'release_date': '2026-04-15',
  'title': 'Balls Up',
  'video': False,
  'vote_average': 5.488,
  'vote_count': 81},
 {'adult': False,
  'backdrop_path': '/nHxWyy18SvAZ8jJeemtS8k1UNjM.jpg',
  'genre_ids': [28, 80, 53],
  'id': 1290821,
  'original_language': 'en',
  'original_title': 'Shelter',
  'overview': 'A man living in self-imposed exile on a remote island rescues a young girl from a violent storm, setting off a chain of events that forces him out of seclusion to protect her from enemies tied to his past.',
  'popularity': 217.5428,
  'poster_path': '/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg',
  'release_date': '2026-01-28',
  'title': 'Shelter',
  'video': False,
  'vote_average': 6.775,
  'vote_count': 568},
 {'adult': False,
  'backdrop_path': '/wns4x1GyxCudgOZRyhXKjXVJf3T.jpg',
  'genre_ids': [12, 53, 878],
  'id': 840464,
  'original_language': 'en',
  'original_title': 'Greenland 2: Migration',
  'overview': 'Having found the safety of the Greenland bunker after the comet Clarke decimated the Earth, the Garrity family must now risk everything to embark on a perilous journey across the wasteland of Europe to find a new home.',
  'popularity': 217.9235,
  'poster_path': '/z2tqCJLsw6uEJ8nJV8BsQXGa3dr.jpg',
  'release_date': '2026-01-07',
  'title': 'Greenland 2: Migration',
  'video': False,
  'vote_average': 6.5,
  'vote_count': 882},
 {'adult': False,
  'backdrop_path': '/7lizs4SuEU2ihkkAa0SZ66NtHbl.jpg',
  'genre_ids': [28, 53],
  'id': 1641319,
  'original_language': 'en',
  'original_title': 'Sniper: No Nation',
  'overview': 'Brandon Beckett and Agent Zero lead a rescue mission in Venezuela when their friends are taken hostage.',
  'popularity': 179.0305,
  'poster_path': '/3T9nAX0jAp0iT18ex25BlZEpRDb.jpg',
  'release_date': '2026-04-07',
  'title': 'Sniper: No Nation',
  'video': False,
  'vote_average': 6.2,
  'vote_count': 30},
 {'adult': False,
  'backdrop_path': '/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg',
  'genre_ids': [27, 53, 35],
  'id': 1198994,
  'original_language': 'en',
  'original_title': 'Send Help',
  'overview': "Two colleagues become stranded on a deserted island, the only survivors of a plane crash. On the island, they must overcome past grievances and work together to survive, but ultimately, it's a battle of wills and wits to make it out alive.",
  'popularity': 177.9039,
  'poster_path': '/mjkS2iAgWj3ik1DTjvI15nHZ7yl.jpg',
  'release_date': '2026-01-22',
  'title': 'Send Help',
  'video': False,
  'vote_average': 7.037,
  'vote_count': 1036},
 {'adult': False,
  'backdrop_path': '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
  'genre_ids': [10751, 35, 12, 14, 16],
  'id': 502356,
  'original_language': 'en',
  'original_title': 'The Super Mario Bros. Movie',
  'overview': 'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
  'popularity': 171.9317,
  'poster_path': '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
  'release_date': '2023-04-05',
  'title': 'The Super Mario Bros. Movie',
  'video': False,
  'vote_average': 7.587,
  'vote_count': 10498},
 {'adult': False,
  'backdrop_path': '/zc08qkHtWfZ2cQGQBK1S5yafJmR.jpg',
  'genre_ids': [27, 9648],
  'id': 1304313,
  'original_language': 'en',
  'original_title': "Lee Cronin's The Mummy",
  'overview': 'The young daughter of a journalist disappears into the desert without a trace—eight years later, the broken family is shocked when she is returned to them, as what should be a joyful reunion turns into a living nightmare.',
  'popularity': 168.596,
  'poster_path': '/8L8efNkz8rUmwR7sV0g3vnC9yjn.jpg',
  'release_date': '2026-04-15',
  'title': "Lee Cronin's The Mummy",
  'video': False,
  'vote_average': 6.887,
  'vote_count': 97},
 {'adult': False,
  'backdrop_path': '/vG42HeYtoTFflqwP42wYD7tBuNr.jpg',
  'genre_ids': [80, 53],
  'id': 1171145,
  'original_language': 'en',
  'original_title': 'Crime 101',
  'overview': 'When an elusive thief whose high-stakes heists unfold along the iconic 101 freeway in Los Angeles eyes the score of a lifetime, with hopes of this being his final job, his path collides with a disillusioned insurance broker who is facing her own crossroads. Determined to crack the case, a relentless detective closes in on the operation, raising the stakes even higher.',
  'popularity': 166.6444,
  'poster_path': '/tVvpFIoteRHNnoZMhdnwIVwJpCA.jpg',
  'release_date': '2026-02-11',
  'title': 'Crime 101',
  'video': False,
  'vote_average': 6.979,
  'vote_count': 730},
 {'adult': False,
  'backdrop_path': '/tq3h43fZy0H80vzf47MAY7R9Mxo.jpg',
  'genre_ids': [16, 35, 10751],
  'id': 1297842,
  'original_language': 'en',
  'original_title': 'GOAT',
  'overview': 'A small goat with big dreams gets a once-in-a-lifetime shot to join the pros and play roarball, a high-intensity, co-ed, full-contact sport dominated by the fastest, fiercest animals in the world.',
  'popularity': 149.8169,
  'poster_path': '/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg',
  'release_date': '2026-02-11',
  'title': 'GOAT',
  'video': False,
  'vote_average': 7.913,
  'vote_count': 413},
 {'adult': False,
  'backdrop_path': '/t9J2HXaDuJR7bvIG9XF7mttn4VY.jpg',
  'genre_ids': [27, 9648, 80],
  'id': 1159559,
  'original_language': 'en',
  'original_title': 'Scream 7',
  'overview': 'When a new Ghostface killer emerges in the quiet town where Sidney Prescott has built a new life, her darkest fears are realized as her daughter becomes the next target. Determined to protect her family, Sidney must face the horrors of her past to put an end to the bloodshed once and for all.',
  'popularity': 131.2172,
  'poster_path': '/jjyuk0edLiW8vOSnlfwWCCLpbh5.jpg',
  'release_date': '2026-02-25',
  'title': 'Scream 7',
  'video': False,
  'vote_average': 6.035,
  'vote_count': 767},
 {'adult': False,
  'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
  'genre_ids': [16, 28, 14],
  'id': 1311031,
  'original_language': 'ja',
  'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
  'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
  'popularity': 137.2521,
  'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
  'release_date': '2025-07-18',
  'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
  'video': False,
  'vote_average': 7.678,
  'vote_count': 799},
 {'adult': False,
  'backdrop_path': '/fPfDB0IHOqvmKIzFP9CA51OOS1N.jpg',
  'genre_ids': [27, 53],
  'id': 1010755,
  'original_language': 'en',
  'original_title': 'The Strangers: Chapter 3',
  'overview': 'Tethered by a frightening conclusion, Maya and the Strangers are locked on an unavoidable, unforgiving collision course — a showdown that proves they’re far from strangers now.',
  'popularity': 147.297,
  'poster_path': '/yPHwX78mcwJw3I6YOJ9qh2wQBFr.jpg',
  'release_date': '2026-02-05',
  'title': 'The Strangers: Chapter 3',
  'video': False,
  'vote_average': 5.702,
  'vote_count': 114},
 {'adult': False,
  'backdrop_path': '/qXxFWyur7jFkg2aQgENcXuyYeHF.jpg',
  'genre_ids': [27, 9648],
  'id': 1480387,
  'original_language': 'en',
  'original_title': 'undertone',
  'overview': 'The host of a popular paranormal podcast becomes haunted by terrifying recordings mysteriously sent her way.',
  'popularity': 131.9687,
  'poster_path': '/2PFgFMnrdCPXWiZl1PUvky7Mo9D.jpg',
  'release_date': '2026-03-12',
  'title': 'undertone',
  'video': False,
  'vote_average': 6.687,
  'vote_count': 75},
 {'adult': False,
  'backdrop_path': '/1ytf7rzkZ7RLlMnBdGggQ0ENe6z.jpg',
  'genre_ids': [27, 53],
  'id': 1418657,
  'original_language': 'en',
  'original_title': 'The Yeti',
  'overview': 'When an oil tycoon and a famous adventurer vanish into the harsh winter of remote northern Alaska, a hand-picked rescue team endeavors to bring them home. What they don’t know is that they are trespassing on The Yeti’s territory, and the elements are the least of their worries.',
  'popularity': 108.5458,
  'poster_path': '/zaqEfoKcWkVni2eONhJ7DRhMO8Q.jpg',
  'release_date': '2026-04-04',
  'title': 'The Yeti',
  'video': False,
  'vote_average': 6.894,
  'vote_count': 33},
 {'adult': False,
  'backdrop_path': '/6yeVcxFR0j08vlv2OlL6zbewm4D.jpg',
  'genre_ids': [28, 878, 53],
  'id': 1265609,
  'original_language': 'en',
  'original_title': 'War Machine',
  'overview': 'On one last grueling mission during Army Ranger training, a combat engineer must lead his unit in a fight against a giant otherworldly killing machine.',
  'popularity': 102.4607,
  'poster_path': '/tlPgDzwIE7VYYIIAGCTUOnN4wI1.jpg',
  'release_date': '2026-02-12',
  'title': 'War Machine',
  'video': False,
  'vote_average': 7.244,
  'vote_count': 1470},
 {'adult': False,
  'backdrop_path': '/lgotja3xMoJZbynwHfcQcJAEMWH.jpg',
  'genre_ids': [16, 10751, 9648, 12, 35],
  'id': 1084242,
  'original_language': 'en',
  'original_title': 'Zootopia 2',
  'overview': "After cracking the biggest case in Zootopia's history, rookie cops Judy Hopps and Nick Wilde find themselves on the twisting trail of a great mystery when Gary De'Snake arrives and turns the animal metropolis upside down. To crack the case, Judy and Nick must go undercover to unexpected new parts of town, where their growing partnership is tested like never before.",
  'popularity': 104.9257,
  'poster_path': '/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg',
  'release_date': '2025-11-26',
  'title': 'Zootopia 2',
  'video': False,
  'vote_average': 7.603,
  'vote_count': 2574},
 {'adult': False,
  'backdrop_path': '/pmGkvEWKFDapogIzkG7TqB0aeYE.jpg',
  'genre_ids': [27, 53],
  'id': 1526650,
  'original_language': 'zh',
  'original_title': '泥娃娃',
  'overview': "Hsu-Chuan, who works at a game company, accidentally brings home a broken clay doll from a haunted house while developing a new horror VR game. Unexpectedly, his pregnant wife, Mu-Hua, a cultural relic restorer, develops an obsession with the doll and relentlessly tries to repair it. As strange things begin to happen in the house, Mu-Hua's condition deteriorates, and Hsu-Chuan, at his wits' end, seeks help from a spiritual medium, Ah-Sheng. Meanwhile, the horrifying secret hidden behind the clay doll begins to surface.",
  'popularity': 97.2695,
  'poster_path': '/ifYNeKwpyKUTtjkUExrqTc65L2p.jpg',
  'release_date': '2025-10-09',
  'title': 'Mudborn',
  'video': False,
  'vote_average': 6.729,
  'vote_count': 24},
 {'adult': False,
  'backdrop_path': '/zTnAnYIn0Iv3cn0ZHlzLhou3ybm.jpg',
  'genre_ids': [9648, 53],
  'id': 1368166,
  'original_language': 'en',
  'original_title': 'The Housemaid',
  'overview': 'Trying to escape her past, Millie Calloway accepts a job as a live-in housemaid for the wealthy Nina and Andrew Winchester. But what begins as a dream job quickly unravels into something far more dangerous—a sexy, seductive game of secrets, scandal, and power.',
  'popularity': 97.4376,
  'poster_path': '/cWsBscZzwu5brg9YjNkGewRUvJX.jpg',
  'release_date': '2025-12-18',
  'title': 'The Housemaid',
  'video': False,
  'vote_average': 7.217,
  'vote_count': 1881},
 {'adult': False,
  'backdrop_path': '/avwIERZtWiWa34qShf5biDzAVaF.jpg',
  'genre_ids': [35, 18],
  'id': 1049471,
  'original_language': 'en',
  'original_title': 'Outcome',
  'overview': "Reef Hawk, Hollywood's poster child since age six, is not okay. When he learns about an extortion plot tied to a mysterious video, Reef preemptively sets out on a redemption tour to make amends, confront his demons, and avoid getting canceled.",
  'popularity': 89.173,
  'poster_path': '/kSzcpfbTy2pXHGvrVU2WhQTo6oU.jpg',
  'release_date': '2026-04-06',
  'title': 'Outcome',
  'video': False,
  'vote_average': 5.4,
  'vote_count': 119},
 {'adult': False,
  'backdrop_path': '/7uXzE0ZBkbAeKylOz7cUQF4Yw75.jpg',
  'genre_ids': [18],
  'id': 879945,
  'original_language': 'nl',
  'original_title': "L'homme inconnu",
  'overview': 'Louis, a Flemish writer, decides to isolate himself at the Côte d’Azur, hoping this place will bring him inspiration.',
  'popularity': 88.7901,
  'poster_path': '/4TpBhdaSl5ALHbgeaYOLF8Q3haz.jpg',
  'release_date': '2021-10-16',
  'title': 'The Unknown Man',
  'video': False,
  'vote_average': 7.3,
  'vote_count': 3},
 {'adult': False,
  'backdrop_path': '/l8rKKMU2M9dDULO9CEtDNdWAEUJ.jpg',
  'genre_ids': [878, 27, 14],
  'id': 1159831,
  'original_language': 'en',
  'original_title': 'The Bride!',
  'overview': 'A lonely Frankenstein travels to 1930s Chicago to ask groundbreaking scientist Dr. Euphronious to create a companion for him. The two revive a murdered young woman and The Bride is born. But what ensues is beyond what either of them imagined.',
  'popularity': 91.0492,
  'poster_path': '/lV8YHwGkYZsm6EfIqnhaSz2avKt.jpg',
  'release_date': '2026-03-04',
  'title': 'The Bride!',
  'video': False,
  'vote_average': 6.2,
  'vote_count': 335},

In [25]:
df = pd.DataFrame(all_movies)

In [26]:
df["word_count"] = df["overview"].apply(lambda x: len(str(x).split()))
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,word_count
0,False,/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg,"[10751, 35, 12, 14, 16]",1226863,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,828.4621,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,2026-04-01,The Super Mario Galaxy Movie,False,6.800,529,51
1,False,/1x9e0qWonw634NhIsRdvnneeqvN.jpg,"[10749, 18]",1523145,ru,Твоё сердце будет разбито,High school student Polina is saved from bully...,434.1481,/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg,2026-03-26,Your Heart Will Be Broken,False,6.985,66,57
2,False,/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg,"[878, 12, 14]",83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,329.6580,/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg,2025-12-17,Avatar: Fire and Ash,False,7.400,2650,65
3,False,/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg,"[16, 28, 12, 14]",980431,en,"Avatar: Aang, The Last Airbender","Avatar Aang, the world's last Airbender, learn...",316.0527,/gPiyTLo5GGwtJl0L8TlaJF9r0KE.jpg,2026-10-09,"Avatar: Aang, The Last Airbender",False,0.000,0,51
4,False,/gM1kQRPwOVW1Eos5tVWqcYmHR5S.jpg,"[27, 9648]",1470130,en,The Mortuary Assistant,"Rebecca Owens, a recent mortuary science gradu...",263.8668,/72AoFPC5TY4DfJwXXS9rPwPeReD.jpg,2026-02-13,The Mortuary Assistant,False,5.400,76,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,False,/zb7b40ieuRGiIc9ebIEapneaCsl.jpg,"[18, 28]",59440,en,Warrior,The youngest son of an alcoholic former boxer ...,8.4061,/iM8n4nZJPR2abpnyZ36FUgHiRjr.jpg,2011-09-09,Warrior,False,7.845,4972,40
1996,False,/12RXkIWUXwOHXgAmlxJNIWRGrri.jpg,"[37, 35, 18]",537996,en,The Ballad of Buster Scruggs,Vignettes weaving together the stories of six ...,8.5979,/voxl654m7p36y8FLu8oQD7dfwwK.jpg,2018-11-09,The Ballad of Buster Scruggs,False,7.135,4395,57
1997,False,/lyzI5uFJC2E7sIYCCdaU0oZkDw2.jpg,"[16, 10751, 14]",756,en,Fantasia,Walt Disney's timeless masterpiece is an extra...,8.0663,/5m9njnidjR0syG2gpVPVgcEMB2X.jpg,1940-11-13,Fantasia,False,7.339,3298,34
1998,False,/vDFhaKEMKPIUePtQH2nOwSHfgPy.jpg,"[35, 14, 27]",9374,en,Death Becomes Her,"Madeline is married to Ernest, who was once he...",8.4590,/kkWxyyyWFK5KNk9WVwQuGEC9H9H.jpg,1992-07-30,Death Becomes Her,False,6.776,2940,50
1999,False,/3TeGmKJfkik1D1rIoqGb1aR4k9c.jpg,"[12, 28, 878]",1893,en,Star Wars: Episode I - The Phantom Menace,"Anakin Skywalker, a young slave strong with th...",11.4706,/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg,1999-05-19,Star Wars: Episode I - The Phantom Menace,False,6.572,15715,27

In [27]:
# Remove movies with less than 20 words in the overview, as they may not provide enough information for recommendations.
df = df[df["word_count"] > 20]

In [28]:
len(df)

1879

In [29]:
# To uncrypt the genre ids, we need to make another call to the API.

def get_genres():
    url = "https://api.themoviedb.org/3/genre/movie/list"

    params = {
        "api_key": API_KEY,
        "language": "en-US"
    }

    response = requests.get(url, params=params)

    return response.json()["genres"]

genres = get_genres()

genres

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 80, 'name': 'Crime'},
 {'id': 99, 'name': 'Documentary'},
 {'id': 18, 'name': 'Drama'},
 {'id': 10751, 'name': 'Family'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 36, 'name': 'History'},
 {'id': 27, 'name': 'Horror'},
 {'id': 10402, 'name': 'Music'},
 {'id': 9648, 'name': 'Mystery'},
 {'id': 10749, 'name': 'Romance'},
 {'id': 878, 'name': 'Science Fiction'},
 {'id': 10770, 'name': 'TV Movie'},
 {'id': 53, 'name': 'Thriller'},
 {'id': 10752, 'name': 'War'},
 {'id': 37, 'name': 'Western'}]

In [30]:
# Change the structure of the genres list
new_genres_dict = {genre["id"]: genre["name"] for genre in genres} 
new_genres_dict

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [31]:
# Create a new column with the genre names instead of the ids.
df["genres"] = df["genre_ids"].apply(lambda ids: [new_genres_dict.get(i) for i in ids] )

C:\Users\34651\AppData\Local\Temp\ipykernel_26264\440369914.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["genres"] = df["genre_ids"].apply(lambda ids: [new_genres_dict.get(i) for i in ids] )

In [32]:
df["genres"]

0       [Family, Comedy, Adventure, Fantasy, Animation]
1                                      [Romance, Drama]
2                 [Science Fiction, Adventure, Fantasy]
3               [Animation, Action, Adventure, Fantasy]
4                                     [Horror, Mystery]
                             ...
1995                                    [Drama, Action]
1996                           [Western, Comedy, Drama]
1997                       [Animation, Family, Fantasy]
1998                          [Comedy, Fantasy, Horror]
1999               [Adventure, Action, Science Fiction]
Name: genres, Length: 1879, dtype: object

In [33]:
# Make sure that the genres columns has no errors
df["errors"] = df["genres"].apply(lambda ids: any(i not in new_genres_dict.values() for i in ids))

# If it is false, there is no erros, if it is true, there is an error.
df[df["errors"] == True]

C:\Users\34651\AppData\Local\Temp\ipykernel_26264\281246137.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["errors"] = df["genres"].apply(lambda ids: any(i not in new_genres_dict.values() for i in ids))

Empty DataFrame
Columns: [adult, backdrop_path, genre_ids, id, original_language, original_title, overview, popularity, poster_path, release_date, title, video, vote_average, vote_count, word_count, genres, errors]
Index: []

In [34]:
# Check if the genres_columns has any null values or empty lists.
len(df[df["genres"].isnull() | (df["genres"].apply(lambda x: len(x) == 0))])

4

In [35]:
# As there are few rows with empty genres, we can drop them.
df = df[~(df["genres"].isnull() | (df["genres"].apply(lambda x: len(x) == 0)))]

In [36]:
df.columns

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'release_date', 'title', 'video', 'vote_average', 'vote_count',
       'word_count', 'genres', 'errors'],
      dtype='object')

In [37]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,word_count,genres,errors
0,False,/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg,"[10751, 35, 12, 14, 16]",1226863,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,828.4621,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,2026-04-01,The Super Mario Galaxy Movie,False,6.800,529,51,"[Family, Comedy, Adventure, Fantasy, Animation]",False
1,False,/1x9e0qWonw634NhIsRdvnneeqvN.jpg,"[10749, 18]",1523145,ru,Твоё сердце будет разбито,High school student Polina is saved from bully...,434.1481,/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg,2026-03-26,Your Heart Will Be Broken,False,6.985,66,57,"[Romance, Drama]",False
2,False,/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg,"[878, 12, 14]",83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,329.6580,/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg,2025-12-17,Avatar: Fire and Ash,False,7.400,2650,65,"[Science Fiction, Adventure, Fantasy]",False
3,False,/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg,"[16, 28, 12, 14]",980431,en,"Avatar: Aang, The Last Airbender","Avatar Aang, the world's last Airbender, learn...",316.0527,/gPiyTLo5GGwtJl0L8TlaJF9r0KE.jpg,2026-10-09,"Avatar: Aang, The Last Airbender",False,0.000,0,51,"[Animation, Action, Adventure, Fantasy]",False
4,False,/gM1kQRPwOVW1Eos5tVWqcYmHR5S.jpg,"[27, 9648]",1470130,en,The Mortuary Assistant,"Rebecca Owens, a recent mortuary science gradu...",263.8668,/72AoFPC5TY4DfJwXXS9rPwPeReD.jpg,2026-02-13,The Mortuary Assistant,False,5.400,76,43,"[Horror, Mystery]",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,False,/zb7b40ieuRGiIc9ebIEapneaCsl.jpg,"[18, 28]",59440,en,Warrior,The youngest son of an alcoholic former boxer ...,8.4061,/iM8n4nZJPR2abpnyZ36FUgHiRjr.jpg,2011-09-09,Warrior,False,7.845,4972,40,"[Drama, Action]",False
1996,False,/12RXkIWUXwOHXgAmlxJNIWRGrri.jpg,"[37, 35, 18]",537996,en,The Ballad of Buster Scruggs,Vignettes weaving together the stories of six ...,8.5979,/voxl654m7p36y8FLu8oQD7dfwwK.jpg,2018-11-09,The Ballad of Buster Scruggs,False,7.135,4395,57,"[Western, Comedy, Drama]",False
1997,False,/lyzI5uFJC2E7sIYCCdaU0oZkDw2.jpg,"[16, 10751, 14]",756,en,Fantasia,Walt Disney's timeless masterpiece is an extra...,8.0663,/5m9njnidjR0syG2gpVPVgcEMB2X.jpg,1940-11-13,Fantasia,False,7.339,3298,34,"[Animation, Family, Fantasy]",False
1998,False,/vDFhaKEMKPIUePtQH2nOwSHfgPy.jpg,"[35, 14, 27]",9374,en,Death Becomes Her,"Madeline is married to Ernest, who was once he...",8.4590,/kkWxyyyWFK5KNk9WVwQuGEC9H9H.jpg,1992-07-30,Death Becomes Her,False,6.776,2940,50,"[Comedy, Fantasy, Horror]",False
1999,False,/3TeGmKJfkik1D1rIoqGb1aR4k9c.jpg,"[12, 28, 878]",1893,en,Star Wars: Episode I - The Phantom Menace,"Anakin Skywalker, a young slave strong with th...",11.4706,/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg,1999-05-19,Star Wars: Episode I - The Phantom Menace,False,6.572,15715,27,"[Adventure, Action, Science Fiction]",False

In [38]:
df.columns

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'release_date', 'title', 'video', 'vote_average', 'vote_count',
       'word_count', 'genres', 'errors'],
      dtype='object')

In [39]:
important_columns = ['adult', 'id', 'original_language',
       'original_title', 'overview', 'popularity',
       'release_date', 'title', 'vote_average', 'vote_count',
       'genres']

In [40]:
df_final = df[important_columns]
df_final

,adult,id,original_language,original_title,overview,popularity,release_date,title,vote_average,vote_count,genres
0,False,1226863,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,828.4621,2026-04-01,The Super Mario Galaxy Movie,6.800,529,"[Family, Comedy, Adventure, Fantasy, Animation]"
1,False,1523145,ru,Твоё сердце будет разбито,High school student Polina is saved from bully...,434.1481,2026-03-26,Your Heart Will Be Broken,6.985,66,"[Romance, Drama]"
2,False,83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,329.6580,2025-12-17,Avatar: Fire and Ash,7.400,2650,"[Science Fiction, Adventure, Fantasy]"
3,False,980431,en,"Avatar: Aang, The Last Airbender","Avatar Aang, the world's last Airbender, learn...",316.0527,2026-10-09,"Avatar: Aang, The Last Airbender",0.000,0,"[Animation, Action, Adventure, Fantasy]"
4,False,1470130,en,The Mortuary Assistant,"Rebecca Owens, a recent mortuary science gradu...",263.8668,2026-02-13,The Mortuary Assistant,5.400,76,"[Horror, Mystery]"
...,...,...,...,...,...,...,...,...,...,...,...
1995,False,59440,en,Warrior,The youngest son of an alcoholic former boxer ...,8.4061,2011-09-09,Warrior,7.845,4972,"[Drama, Action]"
1996,False,537996,en,The Ballad of Buster Scruggs,Vignettes weaving together the stories of six ...,8.5979,2018-11-09,The Ballad of Buster Scruggs,7.135,4395,"[Western, Comedy, Drama]"
1997,False,756,en,Fantasia,Walt Disney's timeless masterpiece is an extra...,8.0663,1940-11-13,Fantasia,7.339,3298,"[Animation, Family, Fantasy]"
1998,False,9374,en,Death Becomes Her,"Madeline is married to Ernest, who was once he...",8.4590,1992-07-30,Death Becomes Her,6.776,2940,"[Comedy, Fantasy, Horror]"
1999,False,1893,en,Star Wars: Episode I - The Phantom Menace,"Anakin Skywalker, a young slave strong with th...",11.4706,1999-05-19,Star Wars: Episode I - The Phantom Menace,6.572,15715,"[Adventure, Action, Science Fiction]"

In [41]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1875 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              1875 non-null   bool
 1   id                 1875 non-null   int64
 2   original_language  1875 non-null   object
 3   original_title     1875 non-null   object
 4   overview           1875 non-null   object
 5   popularity         1875 non-null   float64
 6   release_date       1875 non-null   object
 7   title              1875 non-null   object
 8   vote_average       1875 non-null   float64
 9   vote_count         1875 non-null   int64
 10  genres             1875 non-null   object
dtypes: bool(1), float64(2), int64(2), object(6)
memory usage: 163.0+ KB

In [42]:
# We are going to create a column called "weighted_rating" that will be a weighted average of the vote_average and the popularity of the movie. This will help us to have a better recommendation system.
# This formula computes a weighted rating that balances a movie’s own average rating with the global average rating, giving more influence to movies with a higher number of votes. It reduces the bias of movies with few votes by gradually trusting the global mean when the vote count is low and the movie’s own rating when the vote count is high.
df_final["weighted_rating"] = (
    df_final["vote_count"] / (df_final["vote_count"] + 1000) * df_final["vote_average"]
    + 1000 / (df_final["vote_count"] + 1000) * df_final["vote_average"].mean()
)

C:\Users\34651\AppData\Local\Temp\ipykernel_26264\1480674201.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["weighted_rating"] = (

In [43]:
df_final.columns

Index(['adult', 'id', 'original_language', 'original_title', 'overview',
       'popularity', 'release_date', 'title', 'vote_average', 'vote_count',
       'genres', 'weighted_rating'],
      dtype='object')

In [44]:
# We are going to normalize the numeric columns.
# Normalize the numeric columns
# Delete the vote_count column as it is not useful for the recommendation system and it is highly correlated with the weighted_rating column.
df_final2 = df_final.copy()
scaler = MinMaxScaler()
df_final2[["popularity", "vote_average", "weighted_rating"]] = scaler.fit_transform(df_final2[["popularity", "vote_average", "weighted_rating"]])

In [45]:
df_final2 = df_final2.drop(columns=["vote_count"])

In [46]:
# We are going to create a new column called "content" with the information of the title, overview and genres of the movie.
# We have to apply a lambda function to the genres column to convert the list of genres into a string.
df_final2["genres_text"] = df_final2["genres"].apply(lambda x: " ".join(x))
df_final2["content"] = (
    "id: " + df_final2["id"].astype(str) + ". " +
    "title: " + df_final2["title"].fillna("") + ". " +
    "overview: " + df_final2["overview"].fillna("") + ". " +
    "genres: " + df_final2["genres_text"].fillna("")
)

df_final2

,adult,id,original_language,original_title,overview,popularity,release_date,title,vote_average,genres,weighted_rating,genres_text,content
0,False,1226863,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,1.000000,2026-04-01,The Super Mario Galaxy Movie,0.743169,"[Family, Comedy, Adventure, Fantasy, Animation]",0.519964,Family Comedy Adventure Fantasy Animation,id: 1226863. title: The Super Mario Galaxy Mov...
1,False,1523145,ru,Твоё сердце будет разбито,High school student Polina is saved from bully...,0.521580,2026-03-26,Your Heart Will Be Broken,0.763388,"[Romance, Drama]",0.521468,Romance Drama,id: 1523145. title: Your Heart Will Be Broken....
2,False,83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,0.394803,2025-12-17,Avatar: Fire and Ash,0.808743,"[Science Fiction, Adventure, Fantasy]",0.633793,Science Fiction Adventure Fantasy,id: 83533. title: Avatar: Fire and Ash. overvi...
3,False,980431,en,"Avatar: Aang, The Last Airbender","Avatar Aang, the world's last Airbender, learn...",0.378295,2026-10-09,"Avatar: Aang, The Last Airbender",0.000000,"[Animation, Action, Adventure, Fantasy]",0.518212,Animation Action Adventure Fantasy,"id: 980431. title: Avatar: Aang, The Last Airb..."
4,False,1470130,en,The Mortuary Assistant,"Rebecca Owens, a recent mortuary science gradu...",0.314978,2026-02-13,The Mortuary Assistant,0.590164,"[Horror, Mystery]",0.493168,Horror Mystery,id: 1470130. title: The Mortuary Assistant. ov...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,False,59440,en,Warrior,The youngest son of an alcoholic former boxer ...,0.005029,2011-09-09,Warrior,0.857377,"[Drama, Action]",0.745924,Drama Action,id: 59440. title: Warrior. overview: The young...
1996,False,537996,en,The Ballad of Buster Scruggs,Vignettes weaving together the stories of six ...,0.005261,2018-11-09,The Ballad of Buster Scruggs,0.779781,"[Western, Comedy, Drama]",0.592443,Western Comedy Drama,id: 537996. title: The Ballad of Buster Scrugg...
1997,False,756,en,Fantasia,Walt Disney's timeless masterpiece is an extra...,0.004616,1940-11-13,Fantasia,0.802077,"[Animation, Family, Fantasy]",0.628345,Animation Family Fantasy,id: 756. title: Fantasia. overview: Walt Disne...
1998,False,9374,en,Death Becomes Her,"Madeline is married to Ernest, who was once he...",0.005093,1992-07-30,Death Becomes Her,0.740546,"[Comedy, Fantasy, Horror]",0.517391,Comedy Fantasy Horror,id: 9374. title: Death Becomes Her. overview: ...
1999,False,1893,en,Star Wars: Episode I - The Phantom Menace,"Anakin Skywalker, a young slave strong with th...",0.008747,1999-05-19,Star Wars: Episode I - The Phantom Menace,0.718251,"[Adventure, Action, Science Fiction]",0.467907,Adventure Action Science Fiction,id: 1893. title: Star Wars: Episode I - The Ph...

In [47]:
# Drop duplicates grouping by id, as it is the primary key of the table.
df_final2 = df_final2.drop_duplicates(subset=["id"])

# Create a column with the year of the release date, as it can be useful for the recommendation system.
df_final2["release_year"] = pd.to_datetime(df_final2["release_date"], errors="coerce").dt.year

df_final2

C:\Users\34651\AppData\Local\Temp\ipykernel_26264\2722012765.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final2["release_year"] = pd.to_datetime(df_final2["release_date"], errors="coerce").dt.year

,adult,id,original_language,original_title,overview,popularity,release_date,title,vote_average,genres,weighted_rating,genres_text,content,release_year
0,False,1226863,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,1.000000,2026-04-01,The Super Mario Galaxy Movie,0.743169,"[Family, Comedy, Adventure, Fantasy, Animation]",0.519964,Family Comedy Adventure Fantasy Animation,id: 1226863. title: The Super Mario Galaxy Mov...,2026.0
1,False,1523145,ru,Твоё сердце будет разбито,High school student Polina is saved from bully...,0.521580,2026-03-26,Your Heart Will Be Broken,0.763388,"[Romance, Drama]",0.521468,Romance Drama,id: 1523145. title: Your Heart Will Be Broken....,2026.0
2,False,83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,0.394803,2025-12-17,Avatar: Fire and Ash,0.808743,"[Science Fiction, Adventure, Fantasy]",0.633793,Science Fiction Adventure Fantasy,id: 83533. title: Avatar: Fire and Ash. overvi...,2025.0
3,False,980431,en,"Avatar: Aang, The Last Airbender","Avatar Aang, the world's last Airbender, learn...",0.378295,2026-10-09,"Avatar: Aang, The Last Airbender",0.000000,"[Animation, Action, Adventure, Fantasy]",0.518212,Animation Action Adventure Fantasy,"id: 980431. title: Avatar: Aang, The Last Airb...",2026.0
4,False,1470130,en,The Mortuary Assistant,"Rebecca Owens, a recent mortuary science gradu...",0.314978,2026-02-13,The Mortuary Assistant,0.590164,"[Horror, Mystery]",0.493168,Horror Mystery,id: 1470130. title: The Mortuary Assistant. ov...,2026.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,False,59440,en,Warrior,The youngest son of an alcoholic former boxer ...,0.005029,2011-09-09,Warrior,0.857377,"[Drama, Action]",0.745924,Drama Action,id: 59440. title: Warrior. overview: The young...,2011.0
1996,False,537996,en,The Ballad of Buster Scruggs,Vignettes weaving together the stories of six ...,0.005261,2018-11-09,The Ballad of Buster Scruggs,0.779781,"[Western, Comedy, Drama]",0.592443,Western Comedy Drama,id: 537996. title: The Ballad of Buster Scrugg...,2018.0
1997,False,756,en,Fantasia,Walt Disney's timeless masterpiece is an extra...,0.004616,1940-11-13,Fantasia,0.802077,"[Animation, Family, Fantasy]",0.628345,Animation Family Fantasy,id: 756. title: Fantasia. overview: Walt Disne...,1940.0
1998,False,9374,en,Death Becomes Her,"Madeline is married to Ernest, who was once he...",0.005093,1992-07-30,Death Becomes Her,0.740546,"[Comedy, Fantasy, Horror]",0.517391,Comedy Fantasy Horror,id: 9374. title: Death Becomes Her. overview: ...,1992.0
1999,False,1893,en,Star Wars: Episode I - The Phantom Menace,"Anakin Skywalker, a young slave strong with th...",0.008747,1999-05-19,Star Wars: Episode I - The Phantom Menace,0.718251,"[Adventure, Action, Science Fiction]",0.467907,Adventure Action Science Fiction,id: 1893. title: Star Wars: Episode I - The Ph...,1999.0

In [48]:
# Cast the release_year to string
df_final2["release_year"] = df_final2["release_year"].astype("Int64")
df_final2

C:\Users\34651\AppData\Local\Temp\ipykernel_26264\3167087810.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final2["release_year"] = df_final2["release_year"].astype("Int64")

,adult,id,original_language,original_title,overview,popularity,release_date,title,vote_average,genres,weighted_rating,genres_text,content,release_year
0,False,1226863,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,1.000000,2026-04-01,The Super Mario Galaxy Movie,0.743169,"[Family, Comedy, Adventure, Fantasy, Animation]",0.519964,Family Comedy Adventure Fantasy Animation,id: 1226863. title: The Super Mario Galaxy Mov...,2026
1,False,1523145,ru,Твоё сердце будет разбито,High school student Polina is saved from bully...,0.521580,2026-03-26,Your Heart Will Be Broken,0.763388,"[Romance, Drama]",0.521468,Romance Drama,id: 1523145. title: Your Heart Will Be Broken....,2026
2,False,83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,0.394803,2025-12-17,Avatar: Fire and Ash,0.808743,"[Science Fiction, Adventure, Fantasy]",0.633793,Science Fiction Adventure Fantasy,id: 83533. title: Avatar: Fire and Ash. overvi...,2025
3,False,980431,en,"Avatar: Aang, The Last Airbender","Avatar Aang, the world's last Airbender, learn...",0.378295,2026-10-09,"Avatar: Aang, The Last Airbender",0.000000,"[Animation, Action, Adventure, Fantasy]",0.518212,Animation Action Adventure Fantasy,"id: 980431. title: Avatar: Aang, The Last Airb...",2026
4,False,1470130,en,The Mortuary Assistant,"Rebecca Owens, a recent mortuary science gradu...",0.314978,2026-02-13,The Mortuary Assistant,0.590164,"[Horror, Mystery]",0.493168,Horror Mystery,id: 1470130. title: The Mortuary Assistant. ov...,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,False,59440,en,Warrior,The youngest son of an alcoholic former boxer ...,0.005029,2011-09-09,Warrior,0.857377,"[Drama, Action]",0.745924,Drama Action,id: 59440. title: Warrior. overview: The young...,2011
1996,False,537996,en,The Ballad of Buster Scruggs,Vignettes weaving together the stories of six ...,0.005261,2018-11-09,The Ballad of Buster Scruggs,0.779781,"[Western, Comedy, Drama]",0.592443,Western Comedy Drama,id: 537996. title: The Ballad of Buster Scrugg...,2018
1997,False,756,en,Fantasia,Walt Disney's timeless masterpiece is an extra...,0.004616,1940-11-13,Fantasia,0.802077,"[Animation, Family, Fantasy]",0.628345,Animation Family Fantasy,id: 756. title: Fantasia. overview: Walt Disne...,1940
1998,False,9374,en,Death Becomes Her,"Madeline is married to Ernest, who was once he...",0.005093,1992-07-30,Death Becomes Her,0.740546,"[Comedy, Fantasy, Horror]",0.517391,Comedy Fantasy Horror,id: 9374. title: Death Becomes Her. overview: ...,1992
1999,False,1893,en,Star Wars: Episode I - The Phantom Menace,"Anakin Skywalker, a young slave strong with th...",0.008747,1999-05-19,Star Wars: Episode I - The Phantom Menace,0.718251,"[Adventure, Action, Science Fiction]",0.467907,Adventure Action Science Fiction,id: 1893. title: Star Wars: Episode I - The Ph...,1999

In [49]:
df_final2.columns

Index(['adult', 'id', 'original_language', 'original_title', 'overview',
       'popularity', 'release_date', 'title', 'vote_average', 'genres',
       'weighted_rating', 'genres_text', 'content', 'release_year'],
      dtype='object')

In [50]:
# Drop the column Original title as it is not useful
df_final2 = df_final2.drop(columns = ["original_title"])
df_final2

,adult,id,original_language,overview,popularity,release_date,title,vote_average,genres,weighted_rating,genres_text,content,release_year
0,False,1226863,en,Having thwarted Bowser's previous plot to marr...,1.000000,2026-04-01,The Super Mario Galaxy Movie,0.743169,"[Family, Comedy, Adventure, Fantasy, Animation]",0.519964,Family Comedy Adventure Fantasy Animation,id: 1226863. title: The Super Mario Galaxy Mov...,2026
1,False,1523145,ru,High school student Polina is saved from bully...,0.521580,2026-03-26,Your Heart Will Be Broken,0.763388,"[Romance, Drama]",0.521468,Romance Drama,id: 1523145. title: Your Heart Will Be Broken....,2026
2,False,83533,en,In the wake of the devastating war against the...,0.394803,2025-12-17,Avatar: Fire and Ash,0.808743,"[Science Fiction, Adventure, Fantasy]",0.633793,Science Fiction Adventure Fantasy,id: 83533. title: Avatar: Fire and Ash. overvi...,2025
3,False,980431,en,"Avatar Aang, the world's last Airbender, learn...",0.378295,2026-10-09,"Avatar: Aang, The Last Airbender",0.000000,"[Animation, Action, Adventure, Fantasy]",0.518212,Animation Action Adventure Fantasy,"id: 980431. title: Avatar: Aang, The Last Airb...",2026
4,False,1470130,en,"Rebecca Owens, a recent mortuary science gradu...",0.314978,2026-02-13,The Mortuary Assistant,0.590164,"[Horror, Mystery]",0.493168,Horror Mystery,id: 1470130. title: The Mortuary Assistant. ov...,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,False,59440,en,The youngest son of an alcoholic former boxer ...,0.005029,2011-09-09,Warrior,0.857377,"[Drama, Action]",0.745924,Drama Action,id: 59440. title: Warrior. overview: The young...,2011
1996,False,537996,en,Vignettes weaving together the stories of six ...,0.005261,2018-11-09,The Ballad of Buster Scruggs,0.779781,"[Western, Comedy, Drama]",0.592443,Western Comedy Drama,id: 537996. title: The Ballad of Buster Scrugg...,2018
1997,False,756,en,Walt Disney's timeless masterpiece is an extra...,0.004616,1940-11-13,Fantasia,0.802077,"[Animation, Family, Fantasy]",0.628345,Animation Family Fantasy,id: 756. title: Fantasia. overview: Walt Disne...,1940
1998,False,9374,en,"Madeline is married to Ernest, who was once he...",0.005093,1992-07-30,Death Becomes Her,0.740546,"[Comedy, Fantasy, Horror]",0.517391,Comedy Fantasy Horror,id: 9374. title: Death Becomes Her. overview: ...,1992
1999,False,1893,en,"Anakin Skywalker, a young slave strong with th...",0.008747,1999-05-19,Star Wars: Episode I - The Phantom Menace,0.718251,"[Adventure, Action, Science Fiction]",0.467907,Adventure Action Science Fiction,id: 1893. title: Star Wars: Episode I - The Ph...,1999

In [51]:
# Data is cleaned so we can use it for the recommendation system. We will save it as a csv file and in a PostgreSQL database.

df_final2.to_csv("movies_information.csv", index=False)

In [4]:
# comand to save the dataframe in a PostgreSQL database:

# docker run --name postgres-db \
#-e POSTGRES_USER=admin \
#-e POSTGRES_PASSWORD=admin \
#-e POSTGRES_DB=movies_db \
#-p 5432:5432 \
#-d postgres

df_final2 = pd.read_csv("data\movies_information_with_embeddings_all.csv")

engine = create_engine("postgresql://admin:admin@localhost:5432/movies_db")

In [5]:
# Prove that all is working well
with engine.connect() as connection:
    result = connection.execute(text("SELECT 1"))
    print(result.fetchone())

(1,)

In [6]:
# Save the Dataframe in the PostgreSQL database
df_final2.to_sql("movies_information", engine, if_exists="replace", index=False)

725

#### Make a query in my Postgres DB

In [2]:
!pip install psycopg2-binary pandas

Requirement already satisfied: psycopg2-binary in c:\users\34651\desktop\python_projects\movie-recomendation-system\.venv\lib\site-packages (2.9.12)
Requirement already satisfied: pandas in c:\users\34651\desktop\python_projects\movie-recomendation-system\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\34651\desktop\python_projects\movie-recomendation-system\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\34651\desktop\python_projects\movie-recomendation-system\.venv\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: numpy>=1.22.4 in c:\users\34651\desktop\python_projects\movie-recomendation-system\.venv\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\34651\desktop\python_projects\movie-recomendation-system\.venv\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\34651\desktop\python_projects\movie-recomendation-system\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'C:\Users\34651\Desktop\python_projects\movie-recomendation-system\.venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [40]:
import psycopg2

conn = psycopg2.connect(
    dbname="movies_db",
    user="admin",
    password="admin",
    host="localhost",
    port="5432"
)

conn.rollback()

cur = conn.cursor()

In [41]:
cur.execute("SELECT current_database();")
print(cur.fetchone())

('movies_db',)

In [18]:
conn.rollback()

# Show the name of the columns
cur.execute("""
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'movies';
""")

columnas = cur.fetchall()
for columna in columnas:
    print(columna[0])

vote_average
popularity
weighted_rating
release_year
embedding
id
adult
overview
title
content
original_language
release_date
genres

In [21]:
%pip install tabulate

Collecting tabulate
  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Installing collected packages: tabulate
Successfully installed tabulate-0.9.0
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\34651\Desktop\python_projects\movie-recomendation-system\.venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [44]:
from tabulate import tabulate

conn.rollback()

cur.execute("""
SELECT id, title, vote_average, release_year, genres, weighted_rating
FROM movies
WHERE title ILIKE '%La La Land%';
""")

resultados = cur.fetchall()

# Obtener nombres de columnas
nombres_columnas = [desc[0] for desc in cur.description]

# Mostrar como tabla
print(tabulate(resultados, headers=nombres_columnas, tablefmt="grid"))

+--------+------------+----------------+----------------+--------------------------------+-------------------+
|     id | title      |   vote_average |   release_year | genres                         |   weighted_rating |
+========+============+================+================+================================+===================+
| 313369 | La La Land |       0.863169 |           2016 | ['Comedy', 'Drama', 'Romance'] |           0.79022 |
+--------+------------+----------------+----------------+--------------------------------+-------------------+

In [31]:


from tabulate import tabulate

conn.rollback()

cur.execute("""
SELECT DISTINCT genres
FROM movies
WHERE 'Science Fiction' = ANY(genres);
""")

resultados = cur.fetchall()

# Obtener nombres de columnas
nombres_columnas = [desc[0] for desc in cur.description]

# Mostrar como tabla
print(tabulate(resultados, headers=nombres_columnas, tablefmt="grid"))

+----------------------------------------------------------------------------------------+
| genres                                                                                 |
+========================================================================================+
| ['Animation', 'Family', 'Science Fiction']                                             |
+----------------------------------------------------------------------------------------+
| ['Family', 'Comedy', 'Animation', 'Science Fiction', 'Action']                         |
+----------------------------------------------------------------------------------------+
| ['Thriller', 'Mystery', 'Science Fiction']                                             |
+----------------------------------------------------------------------------------------+
| ['Comedy', 'Drama', 'Science Fiction']                                                 |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Mystery', 'Adventure']                                            |
+----------------------------------------------------------------------------------------+
| ['Fantasy', 'Science Fiction', 'Adventure']                                            |
+----------------------------------------------------------------------------------------+
| ['Comedy', 'Science Fiction', 'Drama']                                                 |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Science Fiction', 'Family', 'Adventure']                                |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Family', 'Adventure', 'Science Fiction', 'Comedy']                      |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Adventure', 'Action']                                             |
+----------------------------------------------------------------------------------------+
| ['Action', 'Crime', 'Science Fiction']                                                 |
+----------------------------------------------------------------------------------------+
| ['Adventure', 'Thriller', 'Science Fiction']                                           |
+----------------------------------------------------------------------------------------+
| ['Action', 'Adventure', 'Comedy', 'Science Fiction', 'Family']                         |
+----------------------------------------------------------------------------------------+
| ['Action', 'Thriller', 'Science Fiction']                                              |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Crime', 'Thriller']                                               |
+----------------------------------------------------------------------------------------+
| ['Action', 'Adventure', 'Science Fiction']                                             |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Comedy', 'Family', 'Science Fiction', 'Adventure']                      |
+----------------------------------------------------------------------------------------+
| ['Action', 'Thriller', 'Drama', 'Science Fiction']                                     |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Thriller', 'Animation']                                           |
+----------------------------------------------------------------------------------------+
| ['Adventure', 'Animation', 'Family', 'Comedy', 'Science Fiction']                      |
+----------------------------------------------------------------------------------------+
| ['Science Fiction']                                                                    |
+----------------------------------------------------------------------------------------+
| ['Action', 'Mystery', 'Science Fiction', 'Thriller']                                   |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Family', 'Comedy', 'Science Fiction', 'Adventure']                      |
+----------------------------------------------------------------------------------------+
| ['Action', 'Comedy', 'Family', 'Science Fiction']                                      |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Adventure', 'Family']                                             |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Adventure', 'Animation', 'Family', 'Fantasy']                     |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Family', 'Adventure', 'Science Fiction']                                |
+----------------------------------------------------------------------------------------+
| ['Family', 'Animation', 'Science Fiction', 'Fantasy', 'Comedy']                        |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Drama']                                                           |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Action', 'Adventure', 'Thriller']                                 |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Horror', 'Action']                                                |
+----------------------------------------------------------------------------------------+
| ['Adventure', 'Action', 'Science Fiction']                                             |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Action', 'Adventure', 'Comedy']                                   |
+----------------------------------------------------------------------------------------+
| ['Adventure', 'Comedy', 'Fantasy', 'Science Fiction']                                  |
+----------------------------------------------------------------------------------------+
| ['Comedy', 'Family', 'Animation', 'Science Fiction']                                   |
+----------------------------------------------------------------------------------------+
| ['Family', 'Comedy', 'Adventure', 'Animation', 'Science Fiction']                      |
+----------------------------------------------------------------------------------------+
| ['Crime', 'Action', 'Science Fiction']                                                 |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Science Fiction', 'Family', 'Comedy']                                   |
+----------------------------------------------------------------------------------------+
| ['Action', 'Horror', 'Science Fiction']                                                |
+----------------------------------------------------------------------------------------+
| ['Adventure', 'Family', 'Mystery', 'Science Fiction']                                  |
+----------------------------------------------------------------------------------------+
| ['Mystery', 'Science Fiction']                                                         |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Action', 'Drama', 'Science Fiction']                                    |
+----------------------------------------------------------------------------------------+
| ['Action', 'Adventure', 'Comedy', 'Family', 'Science Fiction']                         |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Adventure']                                                       |
+----------------------------------------------------------------------------------------+
| ['Family', 'Action', 'Comedy', 'Adventure', 'Science Fiction']                         |
+----------------------------------------------------------------------------------------+
| ['Comedy', 'Science Fiction', 'Adventure']                                             |
+----------------------------------------------------------------------------------------+
| ['Action', 'Comedy', 'Crime', 'Romance', 'Science Fiction', 'Thriller']                |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Adventure', 'Drama']                                              |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Adventure', 'Fantasy', 'Family', 'Science Fiction']                     |
+----------------------------------------------------------------------------------------+
| ['Family', 'Comedy', 'Animation', 'Science Fiction', 'Crime']                          |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Action']                                                          |
+----------------------------------------------------------------------------------------+
| ['Horror', 'Mystery', 'Science Fiction']                                               |
+----------------------------------------------------------------------------------------+
| ['Adventure', 'Science Fiction', 'Comedy']                                             |
+----------------------------------------------------------------------------------------+
| ['Comedy', 'Science Fiction', 'Crime']                                                 |
+----------------------------------------------------------------------------------------+
| ['Action', 'Fantasy', 'Science Fiction']                                               |
+----------------------------------------------------------------------------------------+
| ['Comedy', 'Science Fiction']                                                          |
+----------------------------------------------------------------------------------------+
| ['Adventure', 'Science Fiction', 'Action']                                             |
+----------------------------------------------------------------------------------------+
| ['Action', 'Horror', 'Science Fiction', 'Thriller']                                    |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Action', 'Drama', 'Thriller']                                     |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Crime']                                                           |
+----------------------------------------------------------------------------------------+
| ['Action', 'Adventure', 'Animation', 'Science Fiction', 'Thriller']                    |
+----------------------------------------------------------------------------------------+
| ['Thriller', 'Science Fiction', 'Mystery', 'Romance']                                  |
+----------------------------------------------------------------------------------------+
| ['Mystery', 'Action', 'Science Fiction']                                               |
+----------------------------------------------------------------------------------------+
| ['Action', 'Drama', 'Science Fiction']                                                 |
+----------------------------------------------------------------------------------------+
| ['Thriller', 'Science Fiction', 'Horror']                                              |
+----------------------------------------------------------------------------------------+
| ['Action', 'Thriller', 'Science Fiction', 'Adventure']                                 |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Action', 'Adventure', 'Comedy', 'Family']                         |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Action', 'Adventure', 'Science Fiction']                                |
+----------------------------------------------------------------------------------------+
| ['Family', 'Animation', 'Science Fiction', 'Adventure']                                |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Mystery', 'Horror']                                               |
+----------------------------------------------------------------------------------------+
| ['Horror', 'Science Fiction', 'Drama']                                                 |
+----------------------------------------------------------------------------------------+
| ['Action', 'Adventure', 'Comedy', 'Science Fiction']                                   |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Action', 'Comedy']                                                |
+----------------------------------------------------------------------------------------+
| ['Comedy', 'Fantasy', 'Science Fiction']                                               |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Horror']                                                          |
+----------------------------------------------------------------------------------------+
| ['Adventure', 'Science Fiction', 'Thriller']                                           |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Drama', 'Romance']                                                |
+----------------------------------------------------------------------------------------+
| ['Thriller', 'Science Fiction']                                                        |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Romance', 'Comedy']                                               |
+----------------------------------------------------------------------------------------+
| ['Thriller', 'Action', 'Science Fiction']                                              |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Fantasy', 'Music', 'Science Fiction']                                   |
+----------------------------------------------------------------------------------------+
| ['Action', 'Science Fiction', 'Adventure']                                             |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Science Fiction', 'Drama', 'Fantasy']                                   |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Action', 'Horror']                                                |
+----------------------------------------------------------------------------------------+
| ['Adventure', 'Comedy', 'Science Fiction']                                             |
+----------------------------------------------------------------------------------------+
| ['Adventure', 'Science Fiction']                                                       |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Thriller', 'Horror']                                              |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Action', 'Comedy', 'Family', 'Science Fiction']                         |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Thriller', 'Comedy']                                              |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Thriller', 'Action']                                              |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Adventure', 'Action', 'Thriller']                                 |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Comedy', 'Action', 'Science Fiction']                                   |
+----------------------------------------------------------------------------------------+
| ['Thriller', 'Science Fiction', 'Drama', 'Horror']                                     |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Thriller', 'Mystery']                                             |
+----------------------------------------------------------------------------------------+
| ['Action', 'Science Fiction', 'Comedy']                                                |
+----------------------------------------------------------------------------------------+
| ['Drama', 'Science Fiction', 'Adventure']                                              |
+----------------------------------------------------------------------------------------+
| ['Animation', 'Family', 'Science Fiction', 'Comedy', 'Adventure']                      |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Drama', 'Adventure']                                              |
+----------------------------------------------------------------------------------------+
| ['Thriller', 'Drama', 'Science Fiction']                                               |
+----------------------------------------------------------------------------------------+
| ['Action', 'Mystery', 'Thriller', 'Science Fiction']                                   |
+----------------------------------------------------------------------------------------+
| ['Horror', 'Drama', 'Science Fiction']                                                 |
+----------------------------------------------------------------------------------------+
| ['Drama', 'Science Fiction', 'War']                                                    |
+----------------------------------------------------------------------------------------+
| ['Family', 'Comedy', 'Adventure', 'Animation', 'Science Fiction', 'Fantasy', 'Action'] |
+----------------------------------------------------------------------------------------+
| ['Action', 'Science Fiction']                                                          |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Horror', 'Thriller']                                              |
+----------------------------------------------------------------------------------------+
| ['Science Fiction', 'Comedy', 'Action']                                                |
+----------------------------------------------------------------------------------------+
| ['Drama', 'Science Fiction', 'Thriller']                                               |
+----------------------------------------------------------------------------------------+
| ['Action', 'Science Fiction', 'Comedy', 'Family']                                      |
+----------------------------------------------------------------------------------------+

In [21]:
conn.rollback()

cur.execute("""
SELECT  DISTINCT EMBEDDING
FROM movies;
""")

rows = cur.fetchall()
rows

[('[-1.7922406,0.24212423,-3.6774147,-0.69136316,-0.0013265571,-0.20784636,-0.1422342,-0.2334718,-0.36156455,-0.37264508,-0.7357561,0.87604713,1.2656784,1.3152814,1.2663773,-0.7871379,0.5404731,-1.1287447,-0.48396343,0.48380512,-1.0360208,0.6095385,-0.5487653,-0.40788794,2.5966012,0.24136038,-0.107516386,-0.24628893,0.008065929,0.6267199,-0.16213007,-0.022115301,-0.4178202,0.41805053,-1.4301919,0.88745236,1.4057753,0.65780556,0.26687178,0.5102855,0.47600308,0.13521431,0.9038925,-0.47438043,0.72758967,-0.7272512,0.30154353,-0.53809845,0.8942334,-0.07145779,-0.2876353,0.032106347,0.37316236,-0.372358,0.83259964,0.087833315,0.100192696,0.3806218,-0.15189718,0.30590472,1.3983032,0.82809293,-0.44706118,0.9407892,0.5412123,-1.2962295,0.16505443,1.2558113,-0.09243817,-1.128858,0.77914464,-0.06520086,0.60237974,0.21295144,-0.5715501,0.107726224,0.1913834,0.4247726,-0.9153204,0.54051226,0.5729336,-0.8137811,1.2347639,-0.2795977,0.63508236,0.095781446,-0.9285483,0.25031725,-1.971188,1.224372,0.21328294,0.44436795,-0.08879478,-0.20265281,-0.27109975,0.57472557,-0.16295506,0.093375705,-0.53236425,0.4069403,-0.43234783,-1.1164736,0.5272338,-0.34152985,0.1526747,1.2312886,-0.3151224,0.14863606,-0.990724,0.06525048,-0.41342652,1.1681355,-0.7053052,-1.112493,0.4812449,-0.12334436,0.763198,0.54232484,0.7865877,0.41842222,0.19673783,-0.09074404,0.3860092,1.1163564,-0.3986897,-0.092904426,-0.28604838,-0.2156734,0.2044118,-1.0138535,-1.0404781,-0.58176357,0.43595663,-0.34002802,0.21581008,0.10057304,-0.2397349,-1.0873668,-0.46822652,0.033853382,0.6995881,0.7277543,-0.097452424,-0.26720965,0.30371124,-0.5233474,0.9808711,-1.0762143,-0.80027264,0.25588104,0.40407953,0.419731,0.017795337,0.72431237,0.37307385,-0.43092874,-0.11671705,0.28069666,-0.7263005,0.1715164,0.0882359,0.2564893,-0.8492313,0.47550866,-0.6400871,-0.8041244,0.46826234,1.5091549,-0.035678785,1.5965941,-0.5847077,-0.69079584,-0.089120165,-0.16480409,0.16723856,-0.8041752,0.6979047,-0.0451738,-1.034664,-0.42890045,1.4444926,-1.8550457,0.7127001,0.77821136,-1.2078797,-0.7858844,0.39086226,-0.13045107,-0.272432,-0.8999372,-0.4285397,0.29161862,-0.12548998,-0.51004493,-1.8887787,-0.07981465,0.3495753,0.3248125,-0.108232975,-1.2165562,-0.3053802,-0.17815986,-0.7614315,0.8616701,-0.7302284,0.5971692,-0.18856116,0.1698342,-0.5314162,0.69200236,0.7778367,-1.142871,-0.59737325,-0.11791304,0.11813184,0.22106558,-0.10029055,-0.36506897,-0.5173078,0.17525887,-0.10902112,-0.3168142,-0.0669127,-0.9729775,0.08269745,-0.46038595,-0.39855054,0.2634989,-0.8567091,0.41894987,0.3187374,-0.4684852,0.33797842,0.36541164,-0.1623341,0.27781895,0.3199217,2.0052133,-0.5575534,-0.29245013,0.051328897,0.07360165,-0.12759489,0.065416805,-1.1294942,0.57455313,-0.59087944,-0.20174259,-0.22654136,1.567627,0.32610363,0.14458215,1.570215,0.27542868,0.21639988,-0.61666256,-0.8201904,0.87957966,0.4526109,-0.19772713,1.413356,-1.7113707,0.5356918,-0.98458177,-0.5333032,-0.82268053,-0.48155594,0.5809658,0.14549306,-0.58526504,0.16985133,0.6860587,-0.63588643,-0.050339103,-0.20204388,-0.38827315,0.517042,0.41439927,-0.1403913,0.25660446,0.1862334,-1.6512364,0.41634247,0.341297,-0.7621796,0.6690308,0.16349086,0.7070363,-0.23815648,-0.13966775,0.2169155,-0.7389689,-0.19410068,1.6501601,0.8472063,0.2518005,0.4629404,0.03775317,0.8007398,-1.2223579,0.3209862,0.50757897,0.17417388,0.16811864,-0.5937535,0.35972655,0.6218844,0.35402986,0.40608597,-0.5824706,-0.9868753,-0.90229475,-0.8160982,0.59319514,-0.14227913,0.21767318,-0.48079765,0.2717637,0.63464665,0.16158631,-0.112787716,-1.0315217,-0.43530697,-0.6896858,-0.3290312,1.5595496,-0.8469002,-0.081052415,-0.33558205,-0.5668068,0.023139233,1.2955742,0.30532798,-1.4125277,-0.027202016,1.26339,0.10283777,0.28263494,-0.7854357,1.444994,0.78558475,-0.33703843,0.1905795,-1.758746,-0.55179906,-0.40098113,-0.34584087,0.08686372,1.3270456,-0.3219722,-0.21855868,-0.61938554,-0.22791807,-0.6709804,-0.30179423,0.20196645,0.0015622973,0.3299913,-0.7239206,0.07939752,1.1569422,0.43919358,-0.08311726,-0.19517636,0.26809725,0.115888745,0.8225527,-0.36581272,0.47619778,1.1159574,-0.36743024,0.049428184,0.29659373,-0.5327936,0.2934439,-0.36677748,-2.4152484,-0.92405736,-0.4374277,0.4862119,-0.20351526,-0.1409693,0.34615085,0.24965894,0.28448358,0.0064104665,0.310521,0.29995906,-0.03064019,0.88607407,-0.25113338,-0.4085445,-0.45310986,-0.35960606,0.27718288,-0.94223064,0.9856359,-0.021572858,-0.18993399,0.68825513,-0.82085454,-0.8078199,0.938908,0.04615391,0.22857012,0.85075116,0.75417405,-1.2171453,0.9235518,-0.62014616,0.20545878,1.2038455,-0.61805534,-0.7402045,0.3677087,0.3819497,0.24271953,-0.2861475,-0.5264329,0.2677618,0.84092134,0.48663568,-0.84038204,0.19013742,0.711167,-0.66526496,1.2436937,1.3013945,-0.1258759,-0.3607755,0.0614447,0.5559315,0.16193098,-0.16243531,-0.104451634,0.07523546,-0.052600954,0.093792215,0.8748393,0.53944,0.46870145,-1.425852,-1.053985,0.5594884,1.0949521,1.5428882,0.95638394,-0.7449802,-1.2850069,0.8436747,0.9281359,0.634418,0.056869898,0.84034634,1.6254389,-1.3130326,0.07380167,0.32100457,0.40586123,0.599535,0.6878694,-0.41360417,-1.1106694,-0.32241234,1.0165123,-0.43529359,0.1700609,-0.885729,0.335483,0.4814629,-1.1640799,0.052192304,0.6172269,-0.7229429,-0.68478453,0.68543476,-0.8833222,-0.3757324,0.78061295,0.990268,0.7958727,0.07920137,-0.9443416,-0.5450212,0.20186862,0.90250605,0.46464005,-0.22300169,0.6590607,0.67878616,-0.24965295,-0.58314157,0.99664754,-0.40763718,-0.02145505,0.28075925,-0.6940761,0.44636145,0.5997657,0.7103804,1.0220271,-0.03670139,-0.7703292,-0.2629174,0.62731504,-0.41796923,0.7619637,-0.6654877,-0.36582595,-0.054952133,-0.3551859,0.56160444,-0.22988552,0.3754197,1.1659997,-0.8323445,0.275409,0.5274995,-0.51926225,1.0372777,0.16051656,-1.4280472,-1.3188634,-0.47124466,-1.1243484,1.1259177,0.47120297,0.08965401,0.09931148,-0.4807146,0.36784446,-0.49842188,-0.33438295,-0.7099192,0.042033125,-0.30431232,-0.071205504,0.5680862,0.45167997,0.25497538,-0.21355301,0.35007346,-0.5492638,-0.7991743,0.581958,-0.20763363,-0.4370012,-0.41038248,0.26067814,-0.15658064,0.72346365,-1.5728656,0.61291355,-0.1403479,-0.3254146,-1.117737,-0.78265584,0.3499318,-0.568228,-0.3817324,-0.011910351,0.5943855,0.5433366,0.91182,0.5344141,-0.28675365,-0.13058384,-0.7182538,0.33254126,0.105773546,-0.044317946,-0.7955138,-0.34052923,-0.67041135,-0.6062947,-0.05654315,-0.19377221,0.85764754,-0.68180966,-0.43651545,0.7689773,-0.98861873,-0.19661885,0.8908529,0.023955723,0.20465946,-0.53513974,-0.698798,-0.33834463,-1.4978435,0.7970699,-0.82799935,0.5572385,0.04205559,-0.3358261,-0.65228325,-0.15956451,0.049503565,-0.47126627,-1.1057833,0.8416083,1.0216597,1.1612734,-0.05510604,-0.23371664,0.69011915,-0.7541595,0.42642796,0.7672277,-0.12647553,0.5878688,0.22363684,0.08827475,-0.457296,0.021651398,-0.005277477,2.3203313,0.35538748,-0.44932353,-0.09141389,-0.35470557,-1.4132024,1.5068188,-0.242578,0.943268,-0.3023047,-1.3822244,-0.332853,-0.7258034,1.0966804,-0.89156824,-0.37379572,-1.3674668,-0.29845065,-1.7987012,-0.17326319,-1.1027156,-0.034586426,-0.018575871,0.6099177,0.4699603,-0.101147056,0.8465985,1.2146122,2.2482297,0.44657865,0.43666402,1.0307418,1.38073,-1.5356333,1.1589694,0.705055,0.22619691,0.9178329,-0.39457056,0.06745565,0.14255843,-0.77114016,-0.83784485,-0.29232317,0.37236443,0.35759598,-0.9282419,0.54505277,0.64777064,0.10755822,0.9339137,-0.52816033,-0.64667714,0.10654923,0.9853452,0.5277155,0.55921304,-1.1845843,-0.025064353,0.073419765,0.8103207,1.3311975,0.19481786,-0.350422,0.36625507,-0.18680112,-0.4356803,-0.8300022,-0.042541355,-1.2044361,0.8686565,-0.9720831,0.06615469,-0.69434184,0.35164067,-1.0662321,-0.4235897,0.004988139,-0.90219724,0.29335296,-1.1374087,-0.4625357,-0.583231,2.428561,0.032348894,1.580782,0.07558192,0.31996354,-0.46899295,-0.77987736,0.55072916,0.33116788,-0.41456497,-0.18169978,0.207982,0.859103,-0.48714754,1.0803319,0.8628393,0.1835928,-0.68429047,-0.38049144,-0.7031167,1.2356869,1.1073843,0.09348305,-0.23757665,-0.4158754,0.077133395,0.09414048,0.851805,-0.44164836,0.40291813,-0.35173428,-0.7097165,0.8581074,-1.3065896,0.406874,-0.28510156,-0.6434919,-0.86781335,-0.2554478,-0.5180632,-0.14426316,-0.7335386,0.061723918,0.6621458,0.7507968,-0.2482756,-1.1482606,-0.9418928,0.45389113,0.324517,-0.05459287,0.4473119,-0.11601882,0.083768286,0.27218333,0.16072664,0.3624217,0.27449173,0.9593853,1.5618558,-0.5811334,0.18162636,-0.042265486,0.24411842,-0.56473154,-0.33142996,-0.106404826,-1.1287754,-0.8773475]',),
 ('[-1.713117,0.41311663,-3.7987676,-1.1332278,-0.4117875,-0.47532177,0.16514516,0.39963305,-0.111339636,-0.76762795,-0.09349245,0.63127416,0.81141573,0.44588885,0.13289018,-0.9459801,0.78742003,-0.55186504,-0.60725677,0.33102885,-1.0073836,0.33920532,-0.32151788,-0.15845971,1.2819208,0.51310295,0.022102961,-0.20634119,-0.67947376,-0.07189487,-0.80137503,-1.1477,-0.40361184,0.05616057,-1.6703176,0.5997937,1.9612408,0.79837286,0.48165587,1.4486027,0.250331,0.4713158,0.18213995,-0.8172261,0.4331436,-0.2980852,0.697897,-0.15821324,0.66895896,-0.1652144,0.3549862,0.23740096,1.0619837,-0.85700744,1.9580648,0.805885,0.22777666,-0.46794197,-0.91859,0.8104162,1.0950187,1.1371094,1.0770704,0.6385138,0.7103368,-1.1712137,-0.012795133,0.94401467,-0.4016234,-1.1013241,0.631293,-0.3814548,-0.3485464,1.1561075,-0.074098244,0.72667587,0.14284714,-0.11482528,0.0719278,0.79314137,0.5362337,-0.58560187,0.32165128,-0.4159162,0.23399878,-0.01140279,-0.6015829,0.21849759,-1.81659,0.5506777,0.44177988,0.11907368,-0.39181125,-0.027423399,-1.0472337,0.3064379,0.3316478,-0.43736547,-0.40684968,0.14653187,-1.0302817,-1.4000314,0.77755034,0.18039039,0.33161813,1.5509142,-0.55225205,0.6333686,-0.7372797,0.032303307,-0.22100343,0.7933336,-0.25255448,-1.8483075,0.8511713,0.03590154,1.6474152,0.33906302,0.68579096,0.90956295,-0.22422192,0.49445954,0.4060712,1.383595,0.21436773,0.124065585,-0.41973543,0.2588688,0.17100453,-0.3634231,-0.08838953,-0.3861197,-0.24446784,-0.0838666,-0.2075017,0.88115335,0.58797914,-0.6394107,-0.24686119,1.1936648,0.822885,-0.1633015,0.44413128,-0.6027762,-0.5646322,-0.5112155,0.91822267,-0.8047604,-0.71508694,0.30906168,-0.030301793,0.27612844,0.5200219,0.12278124,0.9381415,-0.38002837,-0.018077992,0.25333387,-0.62371635,-0.25576347,0.25906512,0.32250425,-1.4999629,0.99828273,-0.24487787,-1.252497,-0.10956333,0.6071028,0.11584704,0.9640323,-0.7902753,-0.37781703,-0.065109484,0.7342309,-0.07928155,-1.2464973,1.2853413,-0.2791688,-0.7041386,-0.1765963,1.6367346,-2.6729698,0.8850797,0.06572487,-0.2932278,-0.65379995,-0.02098403,0.32503068,-0.9672594,-1.055073,-0.3849229,0.01978291,-0.75482655,-0.40531275,-1.1325588,-0.70843893,-0.042238407,-0.0099494895,-0.33138213,-1.1744448,-0.094787575,-0.39790216,-0.52625114,0.14991157,-1.6684982,1.0322721,0.05618705,0.5025832,-0.21754207,0.72946167,1.5057352,-0.5609241,-0.4719508,0.14753386,-0.20391281,-0.26992002,0.07082595,-0.9220769,-0.43746504,-0.24931945,0.76933455,0.9456099,-0.26992518,-0.95465356,0.11799068,1.1351061,-0.60211986,0.31817245,-0.0010271652,-0.02423512,0.06461549,-1.0767022,0.7852925,0.55825126,-0.7837519,0.1351846,0.026476458,1.6718316,-0.4948419,-0.6014497,-0.07958506,0.80428654,0.9523557,-0.39763328,-1.1498219,0.4681433,-0.31146914,-0.6430131,-0.45205593,1.6061631,0.49473396,0.13318989,0.73191047,0.7148215,0.007022678,-0.91759044,-0.38026908,0.79971516,-0.059297424,0.4186112,0.31807095,-1.1061939,0.48721662,-1.1424323,0.5386309,-0.37879565,0.023848884,0.1418717,0.7248601,-0.45315114,1.3928331,0.48110056,0.34429625,0.42868727,-0.1512157,-0.44982243,0.1510932,0.98612756,-0.9716477,0.1330002,0.2438158,-1.1243318,-0.08327382,-0.03184774,-0.28425327,1.1091112,0.039132424,0.4343407,-0.18812162,-0.70444703,-0.3971867,-0.3568431,-0.866524,0.7950103,0.18133,0.040906582,0.3162078,-0.3125284,0.48526955,-0.6863415,0.2508027,1.1913205,0.42497036,0.9510087,-0.84628296,-0.049768105,0.20917387,-0.33619156,0.44655815,0.6438057,-1.031507,-0.27663216,-1.0876143,0.57381713,-1.4371117,0.47464567,-0.19625086,0.18525168,0.090616606,0.7455755,-0.13809444,-0.7532557,-0.048391752,0.41307524,0.31966254,1.0310317,-0.45717537,0.6691689,-0.08557134,-1.2146822,-0.14050217,0.7521274,-0.04588949,-1.1814533,-0.6192176,1.5201312,0.24970023,0.67297775,0.11629163,0.48109448,1.3148714,-0.39654785,0.19759206,-1.7039841,0.28236845,-1.0535998,-1.577478,0.5617726,0.6356442,-0.3909014,-0.048268273,-0.37303343,-0.038386513,0.015022367,-0.026885318,0.076445684,0.16471578,0.37867397,0.24204111,-0.1048179,0.55591416,0.1759934,-0.014337686,-0.65508664,0.014525483,0.39969566,0.80422455,0.1535161,0.9834776,0.63225555,0.36310878,-0.3277208,-0.10444179,-0.16281305,0.11714673,0.112143196,-0.7763299,-0.8794207,-0.6269386,0.43041667,-0.048894707,-0.18696764,0.13992183,1.4401765,0.364071,0.519342,0.17713134,-0.11564091,-0.4596358,0.36527333,-0.40327707,-0.17892906,-0.33950955,-0.9831935,0.4889431,-0.51855594,1.1138452,0.0342029,-1.1978953,0.5208973,-0.815947,-1.0078003,0.87208986,0.28782386,0.027012734,0.6606372,0.08035488,-0.7892124,1.6690854,-0.10804494,0.9661128,1.0013351,-0.5732942,-1.0452468,-0.16805863,0.02647567,0.6952719,-0.59996396,-0.80889523,0.42911673,0.8710314,0.3387145,-0.5097645,0.12280463,0.5440043,-0.20242974,1.3237767,1.1509553,0.20518468,-0.8650312,-0.32588375,1.2855195,-0.22769947,-0.5874138,-0.18394636,0.62026227,0.3171406,0.434451,1.196665,1.1237515,0.54639935,-0.87637603,-0.07537958,-0.07097272,0.36576954,0.99524075,0.57832676,-0.9311555,-0.69198745,1.3785187,0.6376013,0.6503104,0.31372085,-0.15717342,1.2572204,-1.0199068,-0.2038815,0.21441491,0.14629512,0.21553966,0.80727017,0.16863786,-1.6699115,-0.63504624,0.27091095,-0.14707297,-0.09216706,-0.07287229,-0.8624133,0.90275615,-1.1563555,0.17917912,0.27478084,-1.0690899,0.31463742,0.35795093,-0.6603811,-0.25611794,-0.34665728,0.78828424,0.9263153,0.06588981,-0.6373432,0.09605549,0.09020562,0.28566748,-0.004935704,-0.13871744,0.4541194,-0.0043615326,-0.4207643,0.04854211,0.5277403,-0.36758518,0.6426081,-0.38091713,0.54761314,0.10423378,-0.5442512,0.9229363,0.5500155,0.64608365,-0.60858995,0.66577286,0.935315,-0.5623769,0.689246,-1.1855978,-0.46181706,0.38307434,-0.9059234,0.37430784,-0.40706092,0.24422033,1.5512401,-0.59413284,0.6415294,0.9160538,-0.00045915446,-0.09282295,-0.2636945,-1.1380047,-1.0245068,-0.9271327,0.009816864,0.9976211,0.38887125,-1.1355815,0.84165287,0.4228768,-0.30179057,-0.20029224,-0.39015374,-1.1282111,-0.16214235,-0.007880265,-0.32234344,0.53083146,0.28877598,0.54280853,-0.21211572,-0.08144302,-0.7965386,-1.056654,0.0685373,-0.38331154,-0.5483047,0.39578572,0.33877307,-0.24483463,1.6711239,-1.2483506,-0.13764657,1.0646734,0.125696,-0.72877055,-0.55415905,-0.24747337,-0.112800255,-0.92918587,0.422411,0.059051864,0.7830357,0.6460179,1.1367095,0.21945657,-0.025412194,-0.82615167,0.30591843,-0.053399604,0.36072832,-1.7833434,0.010705304,-0.66263527,-0.76260716,-0.3147625,-0.2710235,0.70391834,-0.9214411,-0.39564264,-1.0285941,-0.33083215,0.8888405,0.8851865,-0.14493209,-0.047048617,-0.75955784,-0.6158458,-0.13548692,-1.6151989,-0.030969122,-0.16656947,0.36870232,-0.13749017,-0.08877917,-0.3615975,-0.23553665,-0.7124526,-0.65483475,-1.4058001,-0.4723301,0.8016303,1.1393929,0.46230057,0.44107878,0.1628296,-0.643588,-0.5209082,0.57932955,0.10111128,0.50500953,0.52722436,0.24093781,0.17374416,-0.05514508,-0.36831278,1.8874823,1.277281,0.17012815,-0.9980617,-0.30320194,-1.3177618,1.5166821,-0.5640033,0.92138386,-0.77376,-1.3517526,-0.9315567,-0.8318382,1.2479293,-1.3641038,0.27104676,-1.286235,-0.33904782,-0.5925658,0.4547969,-2.0352433,0.896169,0.8384087,0.19889778,0.73322326,-0.12667386,0.55783933,1.069382,1.5994222,-0.353033,0.678127,0.7366987,1.7868364,-0.8084361,1.6389722,1.1745119,0.333205,0.027289594,-0.35627976,-0.12830545,-0.08328436,-0.8728782,-1.0100199,-0.82083565,0.5572638,-0.12993489,-0.9203385,0.23737134,-0.17196928,-0.2679978,0.005893242,-0.17499657,-0.9272962,-0.10695958,0.9205235,1.1402261,-0.44386455,-1.2177247,0.07837243,0.75892603,1.0113077,1.6130335,-0.6769854,-0.8874511,0.10060198,-0.48399523,-0.2323668,-0.603904,-0.61997044,-1.1507274,0.22801566,-0.68358403,-1.0927056,-0.51299244,-0.40357915,-0.9863206,-0.08722336,-0.21750695,0.13094306,-0.20592327,-0.7572388,-0.37681746,-0.5062629,1.4837625,-0.9276642,1.1283479,0.5290249,0.9610007,-0.8965834,-0.34451485,0.15588777,0.36482266,0.11935915,-0.3237475,0.22970025,0.51607686,-0.59180933,0.061873503,1.062675,0.9813435,-0.036394555,-0.58224213,-0.6317472,0.96700203,1.0434958,0.29202121,-0.89809144,-0.14133663,-0.1824956,0.31827846,0.8674608,-0.64876354,1.2182939,-0.42219368,-0.2501984,0.5410583,-0.4642903,0.14276893,-1.1092472,-0.3429679,-0.7027574,-1.1065975,-0.34602827,-0.7729152,-0.439644,0.04202794,0.7186383,1.1070837,-0.32631698,0.1154513,-0.80090004,0.5831161,0.3583496,-0.9893833,0.64567244,-0.6615147,-0.03643763,0.27141136,0.38701144,0.7848676,0.0940662,1.2170933,0.9688587,0.2303992,0.6670923,-0.9308605,0.23565844,-0.48888716,-0.22122957,0.06567371,-1.3187687,-0.57472116]',),

In [11]:
cur.execute("""
SELECT genres, pg_typeof(genres)
FROM movies
LIMIT 10;
""")

cur.fetchall()

[(['Family', 'Comedy', 'Adventure', 'Fantasy', 'Animation'], 'text[]'),
 (['Romance', 'Drama'], 'text[]'),
 (['Science Fiction', 'Adventure', 'Fantasy'], 'text[]'),
 (['Animation', 'Action', 'Adventure', 'Fantasy'], 'text[]'),
 (['Horror', 'Mystery'], 'text[]'),
 (['Science Fiction', 'Adventure'], 'text[]'),
 (['Animation', 'Family', 'Science Fiction', 'Comedy', 'Adventure'], 'text[]'),
 (['Horror', 'Thriller'], 'text[]'),
 (['Comedy', 'Romance'], 'text[]'),
 (['Comedy', 'Action', 'Adventure'], 'text[]')]

In [17]:
conn.rollback()
cur.execute("""
SELECT id, title, genres
FROM movies
WHERE genres && ARRAY['Comedy']::text[]
LIMIT 10;
""")

cur.fetchall()

[(1226863,
  'The Super Mario Galaxy Movie',
  ['Family', 'Comedy', 'Adventure', 'Fantasy', 'Animation']),
 (1327819,
  'Hoppers',
  ['Animation', 'Family', 'Science Fiction', 'Comedy', 'Adventure']),
 (20222, 'Sex with Love', ['Comedy', 'Romance']),
 (1084577, 'Balls Up', ['Comedy', 'Action', 'Adventure']),
 (1198994, 'Send Help', ['Horror', 'Thriller', 'Comedy']),
 (502356,
  'The Super Mario Bros. Movie',
  ['Family', 'Comedy', 'Adventure', 'Fantasy', 'Animation']),
 (1297842, 'GOAT', ['Animation', 'Comedy', 'Family']),
 (1084242,
  'Zootopia 2',
  ['Animation', 'Family', 'Mystery', 'Adventure', 'Comedy']),
 (1049471, 'Outcome', ['Comedy', 'Drama']),
 (1234731, 'Anaconda', ['Adventure', 'Comedy', 'Horror'])]